apiVersion: v1
kind: Service
metadata:
  name: prerender
  namespace: vue-nginx
  labels:
    run: prerender
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: server
    protocol: TCP
  selector:
    app: prerender