apiVersion: v1
kind: Service
metadata:
  name: vue-nginx
  namespace: vue-nginx
  labels:
    run: vue-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: vue-nginx